import random
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm
fig, (axs1,axs2,axs3) = plt.subplots(1, 3,figsize=(14 ,4))
V = np.load('/tanData/cov_matrices/softmax_100k_Vall.npy')
W = np.load('/tanData/cov_matrices/softmax_100k_Wall.npy')
W1 = np.load('/tanData/cov_matrices/softmax_100k_W0.npy')
W5 = np.load('/tanData/cov_matrices/softmax_100k_W4.npy')
W10 = np.load('/tanData/cov_matrices/softmax_100k_W9.npy')
W16 = np.load('/tanData/cov_matrices/softmax_100k_W15.npy')
axs1.hist(W[-50:].reshape(-1,),bins=100)
axs1.grid(True)
axs1.set_xlabel('Eigen value #',fontsize=20)
axs1.set_ylabel('Eigen value',fontsize=20)
axs1.tick_params(axis='y', labelsize=16)
axs1.tick_params(axis='x', labelsize=16)
axs1.set_title('Histogram of Eigen values (all layers)',fontsize=16)
axs1.set_xscale('log')
axs2.plot(range(len(W)),[np.sum(W[-i-1:])/np.sum(W) for i in range(len(W))],linewidth=3)
axs2.grid(True)
axs2.set_xlabel('# Eigen values',fontsize=20)
axs2.set_ylabel('Cumulative Eigen Energy',fontsize=18)
axs2.set_title('Cumulative Eigen Energy (all layers)',fontsize=16)
axs2.set_xscale('log')
axs2.tick_params(axis='y', labelsize=16)
axs2.tick_params(axis='x', labelsize=16)
axs3.plot(range(len(W1)),[np.sum(W1[-i-1:])/np.sum(W1) for i in range(len(W1))],label='Layer 1',linestyle='solid',linewidth=3)
axs3.plot(range(len(W5)),[np.sum(W5[-i-1:])/np.sum(W5) for i in range(len(W5))],label='Layer 5',linestyle='dotted',linewidth=3)
axs3.plot(range(len(W10)),[np.sum(W10[-i-1:])/np.sum(W10) for i in range(len(W10))],label='Layer 10',linestyle='dashed',linewidth=3)
axs3.plot(range(len(W10)),[np.sum(W16[-i-1:])/np.sum(W16) for i in range(len(W16))],label='Layer 16',linestyle='dashdot',linewidth=3)
axs3.legend(fontsize=14)
axs3.grid(True)
axs3.set_xscale('log')
axs3.tick_params(axis='y', labelsize=16)
axs3.tick_params(axis='x', labelsize=16)
axs3.set_xlabel('# Eigen values',fontsize=20)
axs3.set_ylabel('Cumulative Eigen Energy',fontsize=18)
axs3.set_title('Cumulative Eigen Energy',fontsize=16)
plt.subplots_adjust(left=0.06,bottom=0.2,right=0.99,top=0.9,wspace=0.35,hspace=0.01)
plt.savefig('/root/khainb/figs.pdf')
